name: CI
on:
  push: { }
  pull_request: { }
  workflow_dispatch: { }
  schedule:
    - cron: "0 0 * * *" # Every day at 00:00 UTC

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v7

      - name: Install Rust
        run: |
          rustup update stable
          rustup component add rustfmt clippy
          rustup override set stable

      - name: Build
        run: cargo build --all-targets --locked

      - name: Clippy
        run: cargo clippy -- -Dwarnings

      - name: Format
        run: cargo fmt --check

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v7

      - name: Install Rust
        run: |
          rustup update stable
          rustup override set stable

      - name: Build static website
        run: cargo run --release

      - name: Upload artifact
        if: github.ref == 'refs/heads/main' && github.repository_owner == 'rust-lang'
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./output

  regression:
    name: Regression test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v6

      - name: Install Rust
        run: |
          rustup update stable
          rustup override set stable

      # Do the cloning here rather than via the git2 bindings so that we can
      # ensure that the repo HEAD is checked out at a specific commit and the
      # .mailmap content is static. actions/checkout does not support bare
      # clones
      - name: Clone rust-lang/rust
        run: |
          git clone --bare https://github.com/rust-lang/rust.git $GITHUB_WORKSPACE/repos/rust-lang/rust
          git -C $GITHUB_WORKSPACE/repos/rust-lang/rust branch -f main 0490dd938541ad996c5ad1ec6e274012afe3e1d4

      - name: Build static website
        run: cargo run --release -- csv

      - name: Run tests
        run: cargo test

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.repository_owner == 'rust-lang'
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment

  conclusion:
    name: Conclusion
    needs:
      - test
      - build
      - deploy
    # We need to ensure this job does *not* get skipped if its dependencies fail,
    # because a skipped job is considered a success by GitHub. So we have to
    # overwrite `if:`. We use `!cancelled()` to ensure the job does still not get run
    # when the workflow is canceled manually.
    #
    # ALL THE PREVIOUS JOBS NEED TO BE ADDED TO THE `needs` SECTION OF THIS JOB!
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    steps:
      # Manually check the status of all dependencies. `if: failure()` does not work.
      - name: Conclusion
        run: |
          # Print the dependent jobs to see them in the CI log
          jq -C <<< '${{ toJson(needs) }}'
          # Check if all jobs that we depend on (in the needs array) were successful (or have been skipped).
          jq --exit-status 'all(.result == "success" or .result == "skipped")' <<< '${{ toJson(needs) }}'
